travis:
  secure:
    BINSTAR_TOKEN: WxQTKBDOwAvXkCgqnX+cOgf35QcAEeUI4sS1ESg/jnNg+ctvrQaFMQwRb9UJnOiVyZtuIVWfsS7lHew3JePDHVzRtfH1TtSoQXm0Xw4v4KnMmT0Ld80otQ1PMtHGMFTgXIgX0rr+2x/cEitGO/xZK7yg5rCmEjR4VFAX2dDimdr6bHbw5CuQ2FtoorVpAHnJhN1e5q/SYrzwAnICPOpy9o7q/ccq2X6xGk8aMoCE/9HPqYJxQImNW60NB/wC47DjagIhJaH8fjP32yFqpyxqGw2k5jf5Y2w/ztN+UiL+T3mJABEoY1fj/DK9ohpltdode/3MevWB9RCfbSS+cp4vMuIPfw/SdUMx+HjJjxg5Gb9rBm9mCoZPd1c7pBsQfuw7pbiT0goGh27dGI65GXJJ1qMtDXVf5v/afcfSsveI0p/+u37lhq63ClQcOvG1dsLJLnNxZ7PDLW1nTUaRercMCo/naOrMgji34fyjE9GCpfZkm/4cCJ/Xq0RRnAxC19AAiIZQd6grEK4WPg2v5inAxONdo08qreFT0n++w/tXKOqQZPrJlx83fzIEYNiqI4T5U3mhwJMvVJvTUH4FEsOifyVWG0zmXCL3hpl2uYwV6idyqAMZ59et2L2lO7EN8c0tUi5U6Z5RwWIG5UVP0oZIsLVTgXSBsxjrvbsWv81h1eU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
