travis:
  secure:
    BINSTAR_TOKEN: lfOzWZxmAtdw+qjKjyzfD1JdS1BTHbBLmIZzuuBkqCSTu/PQG/+L0LNwLONqCVB7i0ud/1Nl4o47S10vp7HsQ8jPJbAH46f40VEALlDwogOBEd8+ihFClG6gBU2skAuENlTbcWIWKR9aGFjnRVAe4uSGRgv/0ZJ8VuIt9JXBd3FvbBMXCVLO/B0EOIpWpIm6Z1KRjzB7XMYXTSu9uSYY7h3iyZruBKpyGiNIUWh+nCtgGX3dHy4vU3SiF5FIhn5bZ4tawtm4uBnDanlRKMLmUGZ3UGkbxIRY63SnRf4qlNykCArykp1+Y4ViDDP1P6rzmjf1thS9LeoKgq1G0sZJWyr+CEl4RL4kqhVAtl5kPNijy73fLasWZbsU7V62A6/l04k+/T+k/1EnfMHTosdHWlbvg6UAgA+oyNDwH8QcyutDEwoYOy1fZ/1B2oQU1GCyMgfQ/lFTDnCC3DSDW1OQYkSicAQi9ZpmOhDOp6iXJxwUt+AXIbudVQTNeMut/9I3Nuosvdw27/SDSDB9RTvwXwrSIOv4k5UBn08ScJIbgiIhjOmO1YC18YIIBs/V+pYRB1xr9uV3Pn5gSg52B3tN7kCcQ1KFlx3vlIE7dT48FQDiOIjI+gk1BO+6l/do7YdyDNbnu/NB2wZAp249tlDldes5fYG3HR1mC3OWurBbz9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
