travis:
  secure:
    BINSTAR_TOKEN: fNVBMejW3jfKOhIoID3oXBNRt8DmE+khRyGCJIbp0D+Vyfrx4YItXd5TdBeC8saAWGu0Kw6jxZtl/Le+qFEmRaL5b9JXWdqKm1++MzedxY4pltnH6dRkZmfYz46zc22cJI5qMKsaWAHnhvpSn1vkiSJFl01llVHyJ/RCNaL2I/6zvkFU1++19NybGqMcfBMF6PolmGoI/BpOyyv8GSyhB33GZRkzjJ0SUxM5QgdvQzAt/gHKSvblCBl0opFdAD4zvc3bMtbDqfk+k/WU+ej5/NUl2zDJ/2hSHdOF3ozhUwWmZtpxiiEBauI4ezoRnqVMd7uOau6SJb5EPLGa9fWMwuh4i+QZ8XN4l20+G5HPIS1DmfxXaFv4mWbffzr4p00Glc0Efnf3rGfDnTsvpp/GZK9Vk1dJU/Pdc8O+X3l0G+XSSEKUv48aG3drOEu0ow+KIiBonMarBYAE/ShU6TyEF0xqWEO9UJDcVFutcvZLiJZ8Hd8TrLMbDtLxtrLTC21f49TQdAOaQ89J64OjDBmtz35NvgrnH0UyHbuTaI35W1lgCzgzVgwxx7p6ckw8U9BrlM8DZpnGRFCvxz/BShB1BtNkYlaZYt3EAkMAfxKT/wBuRAq6nTWP2AbsBqnYAjo0/OU2042YKpVy/I7jfg/bf3nZ+O8fdnjGv/cjMrTwQ/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
