travis:
  secure:
    BINSTAR_TOKEN: CECli3TheNYnFIzb4DZ9xeO/PUz+jAR2d7QVjnQGbDEgAitKEfp7wLdrX2JRUbxDPYBOd72vRDt9XIlXBZKvSS2+Eu7rThxtekUTB6ffVjdNRgNoel3170zgXimoyB6m5WDyRc0MIqbOgTcYFbiCGTdJ5jtdEjkFyL/mkdgnmzhrEx5ni6DZ4opCYlDt6oqiaTJeyPACbXJynhq1oVrCF1asjkVe8qKaUBcOjXTdsFA7PIenMLhuXhEnlcA2L0aR6JtpDCuok6Ybqmj1/i7wLYyk4TIqyIOwMlpyN93YbDs6nXsHN+JpwgnxZT3/31aunhpk+cxgfgzkFLelggTFozwtn4wqqtRXWO/DGdb7mcrDv3nAo/6BAasDtp8mREGmat//e7kqyCBF7c6dinIakZAXYd0viC8xqjoqgZlz5SW6vnvG2ADI8oITM7R2+z8qu3c5W0bbKzq9eARDOlEzdYEsL1k/pmiaJUUcNkVQf5fdCtVkZb0jYhchg+6AXjO2qVNsjgo0jEgjx6ou497bqOAOjzCVvPAuRX04C1dkUJdpP0wEejsthIKw7O48k0dY5LQ3DlrKDFwVmJve9jnus6vNmf+8kekU/SFIjg+lu7qF8yjMGqt9NC3Y1zYP6ctE0VVaIvUecHFuGLzHbI5jnPQDDPXmObgcN5uDSKyFGac=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
