travis:
  secure:
    BINSTAR_TOKEN: EoSsMgjSwkdaDHrtBcA5bqyNba+c4mWvX+qbQ0z/8hYp7nGPHNrpa0Lv0h1QkHWMk8nFJzRw1zx21r8fqlYZumDBIDevEmKxb39iGtt3imsazI4O7PSq4kTe6dqiUpo8215X2pOcPXjz82AinYubxfpDxPLQ6NXi+xLoC8iMqjLMRs/tx3a/myq1eMInbbasOe7S8lbZfvd7Gvvb5MDiGQUQSDWY+i3xNBPzuaN86exp6IfT33+FfkGIZrQgOkh8ib0y9ag8V7cHDWIzhkkaoZCoOx8S6i3naLJoX+sqnCd2pJ3+Z8RY/IFE2XXCAdUvh96mJ2H4IIMC1us49ovBkvpQPAKNKJjzfUhQSnIBjQZ+nRbhDfKUdn00P0mxili/pBfZjk7BSG2pZTE/3VKvvaH5ai/rU58o/+63OVSuLVkPnxOs25qj5jsH9dMqcTgTFbzwf/EB3T6fWek+8VtFL8vwkEiqJPvKdZXdpe4m9mMP5ax7dmkXkR7sYMAUL61IuMd+hO+3kcDIM0HmZDwpw8MRlClYGwqwxRcFYdAWqSP5DvozpcHrcQMO4u/yn5xJzQaV58P/RXoKN07GY6NB9lJV8XmNBFTICDtCwPqyN/aqFnSIlRS9bjgQ6ywQ+XFZFnMZI77hibv8D6+33lzgLUO2/yAC99t67PDUSBPdE80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
