travis:
  secure:
    BINSTAR_TOKEN: LLiflo/ByAr6I7yApOXGyLjar2cJyGWprIHgkmt6iJvmazSLM9YKNaE14RjuDW4xszrzzvm1fx5FvaGvkgKei/tebXoW4rZzZLv4ljNPxNPD5GbHaQzGVHDxyCY+231O/xkluTetEc40CsQP4vi0F6iOWYso9HxjYo85Fffrio+8I0v+es8OP94BAjzVH/1k7WrtZzvzs8N5/2HLfyC+J1ayHuAy8LXzXxh47dHXb30ox7fHHxnrlhck+19s6JW+qMeZlAgpEBJd6gSASw+BcL6PU+8ibDHxK8DCbl5AHIxl3RubpBLK9wuBc3tu8TOJlSDbbRHsQ2oOxKDE8hfRcFFXuhVKKd5jCyPpukr+FJyWcOCDPo8UQCOJ0LleUdel7YGu6uR3t5btfsi2JWCIwRWbaHkU1nq146BPsUGIi8dPXgBG2cHVD7TY0rXdXvArZJa8xXnvCXvntUbaWCC8Z9h2QknuSlkJXdMQ9mXZMRnUgMkU/fMvPlv7ErF3FAD4GGonNPmoSQuhkuMA8rVtLOyj1gI6BKJkGykG2Tf1DmsNV8ohNLxnDL5c5Zit1210lvf90Ih/8f0u+rU04vf+gALF+pp6DkNluGvM77mJqG4Vj4A76nnMZ9Xord7XGkbih8OKPqk1VhB2AlxXNewTQW7Gcx4gTmQylFNmcLbJw6o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
