travis:
  secure:
    BINSTAR_TOKEN: DyNgoP7wJs/3dmKuBxaTq1/ww4oOigUNtBtDBYfkbuC2RGz/ORXnhEtn38ppnJOazWU3nB/x3J0j8otLl1BVNBB/CI+EWd54nDyP0gtnJfg+nNHqfHyf+rVcUYAhzpijgwoaUjRhk17+UeQQrnJRYFH4O6oAmWuclrY0EbIeXy4oqZiIA6AwYNTiK9io65xzLgANvHgFAvqFqAq4CVqHjyzX5XEEtdNaznYztCXkyVuUFXfBnMgdvSfdVyfLeJEKd80thExL7G0SyhxZDb9kh95KNZEtUETSDhMaZUbErhNMaLpFc6CDopO5RwWYKOb9ej2lARlzUxipgRKxWCxOR0KJyulgUSdQP0Q6tZbkRlXI1yEzOiLrOY1RD+2Fu4WfQQl7XNeO/S5dmhR1sqduMBa61bAVGk/Ox9wGGZ9Dm7+k5GjR1FxAUdqzn/51bOnUizhjgc0wwMzPjcLsaRjvMCtZUDSTTuBavqO+L0UHQ8FTci4mbGxiWK2TmC2WzPoP1jROx0j6LPL+OFri/fZPx8RoJGZ41Cfu47DGpvyInMdhJaZZygayRSvVmrYVHnOrWYGkJlNGDuMdZ2IbqO/SU4sBEJ4bWNVcOgHOP4IBUVYZV7e7ioDP2HmniuCfRlLPKQo+sV3/A1g21SzgtCo41addUR3R0xYSKnx7Ykgtfc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
