travis:
  secure:
    BINSTAR_TOKEN: UReYPEmPyA0wRlYJ9azaGCa/CiaZX1jyeYaR/I8ZSKSHVMMrTJSt05gcvU+DhgMPQsqsNsq/1vkkcUX7P9Gf83D/neF/kwu5XZGXaawOgpim3Lvbqi9320T3kQy2J4VGfzZC50biQSZMK5xoSfsa++2dgmj8iroR37nAes5fqlmHm6tIvOIQsEx8SVV0GaeSj/AVYyTF+MWTx7ueOXIX2fpxiy/+jsyK0J7m1KfZcJm6fg1E95dmKVFet7CJgbfls7SouFRxvp50f468KErTWRr+B1mG6RUTmLsPs1YilwFxAtYAyqO8yS3wiNIlKrE89x755sDd4264ixHmgYpEuJu8TkFbuyVuUD1AkmuSWc55RnPw1URqPy4EJH9VGwuDnuZOAgSNifd+wPZ/XgBnivS4oHjbFOrB6RQFehj1lh0bbxG/g9zBhpbWmTLcZkyViduUc2n3ki8FU2Oec22gFBn1DQPDHaEK2QQuD8CMcJlHGpek1mbVcfkGb2BLvP5Dv/lyhfIGw8gRxpi/5CAkpIotSv0iG7g0+TCa0U8sj0XNRFNCBAEsq/CSWarCNSGsMxV8FapmIhhcuIrISjNBD9s7k+V1qrXf1SMDtePk0zLYpSZNEtKXKf6fPnonL5u7hYnNqZAunnXenMv+0NO3i2lJEHBVNUEzGbmxZuMCn8w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
