travis:
  secure:
    BINSTAR_TOKEN: OESMjIQxGRBBirse++0xFhaIKnNLD9tutp65hCCfqh21XimBBzSMaHd6wIJVcxeEDzpB4qTuiy3pZ1JCV6H361Wh96ydTak5NoZRHxUy7jGKU0/5RwnjUBpTeiL7XSRJRz6bGTVxMmReIDMlBI4H2L7eayNTdvSOqebUAs7UwTs3TmazudxgFYvXwH8ddqHG6AJcb58QTK5NmWVaLkmwa90/e7BATkA+D+Fh56CPmjWSqftGnoXPpT+9vJyC6SlW2tS0iJ6de7QXdMogDyb6EeKOj5LDOhPPX7DNGhhYSjDPd4ZRxNrF95k2oCXqMCnBpFZNP/HPgtU3gHzdkN9/xAhCA6dHbasKsQlwxGYoZCHIUiZvGVLlQL+1xDfsAyPn0GMjJV8txgS/Ott1BgsP6XESzbZrFIxkZYYk2INqXtsMpn1nvyBOszSJ9GOaxU8quA+C1xHcc4OSjIgTm0v68uQ5XTWy1Wj/XTE9j4atvpTM++e59etW0Sz+M0akGyUKJSotPJuIgCuvka4ufBH1gw/sCNDAhhGlQ9/KDYKsfudGxEvQZxqVMNOK4PYeg4IHMpL+3apUhY4a32kRuieyDfD1tmdFUIMt5bnVh+Z/fSZcC7yg6FHNjSwG3Ew2hQuwcDy7hcItrbI9uBVwF41IUG8zGJyWVSx8JiBaL4AT69E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
