travis:
  secure:
    BINSTAR_TOKEN: gKnfVmLPRGTaL6Lw6lRrT6mJYp8Kr00qIzSQJPQDGKHmIagTOKivAKy9Jvp0rIpRqI+g9betVP45lpBfIDE5hykhCWToucXo0idISEN/SuamJBMjkJjahe5LDtDCIosh+jA/4Xxt4XnOQBvipa6qbdZYgD90vMsvU7nPaBiTh4A4fl7eA7XTodniS+1IifHA15+5TQaJoYSlHn9htHmkRrObFooMioXzyoZC6lqJxR84Q/sNwdzXbgGP9jMtVgG10JYo7/ZRB7YInbmmICCJw8CpRs98JPCUbDzgjeyJCv7FpjyZjlrmuBzLpm72k3HoqmypZUievlX8q9Qcz5NIiHMHEqexB0XdLsszqnSLZpJH37rrPadqkh8QpP6mato5J2NCrK9GzQgp1vUHL1ZxNpX3uhI1vLFPSS1VvKzNWPJNsiPSpf43osMnHZsC6hsCwmf3OeVKKPvKyaV5jbTrGb9UxyVL3V/rvfa4fSxl4KUC26aKt8nZz0tMB8lSjQ9S4cOgtbOu+meZnPFmU4kSBF2/V42zRhzEUt6k2ubJsZdHW4MLBF7gUS7WgmsZ2bdXqqZ37+oYF4ocLICfZmtSMDDNGNqibWYIYiuX0066QaX/fDYMFPUuPD8PKFEdmDXG0iJJU/NKHVIENUXIY8E245utBpdduPE2dN+c8NqPIsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
