travis:
  secure:
    BINSTAR_TOKEN: EzyUEy8QAjs232Ca0Jab9C4K0aPSKnktskNlSBHFYGzatZU2Onf8PDJoL20y1SAzevKzY5/GPQXFut4j7AjvlobfYP/KTZF85waLkxZw6ZW62u81Z++QkVlOhoKdn64hXKAOCfwHDlJ7tnCbHT7mPegEt7PkF8qVHU5O4/zDrEggCekQ2mjC2LEi0KJeTyBsANrtEW57LI0pV7mW0WKL81ucP5+oi3y5Rw7wDJOroGu5BJfbgP2WkHrE3ahjpfqmD+KgUD+e19g9iNeETrPkvUEqjFPFWr/8V8XRW0ZIA0gD+8L95I0hzCdJZ4/PdGR4BAEaqJYJHabM+XCqeGpp0O8TXnUXr8czOoKEvrBqHiPj9HsZsUpCIQS+gudDQz3uCpZLHUC/kD28gpVpmHOSWLxvWCfbNY/bK3aqDUB/mVmjNLE4zlSBMrf8PuzxAXqqYOgfujTOHUNzl6+TUjuVtVqMAWLmubMQbF2Q5j85USOdKrT5Iv614t80J0COrpZYxzucmWeqVYzCwG5KJBTf1+aETsVI+4nybCJx1PXFAf8ifGFY1AC5UPyfKTz/x8UWgXT9/U8dnKt2dzQxfR/DykY/knSynNxNNatAMEAjLImeT02wjkS7SufQKe4e//Iggxp0T/EKT6EVsmI1GoV/wPoNwc6I05M8TLKSBaIdbDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
