travis:
  secure:
    BINSTAR_TOKEN: FAdNeOANtp4wHMU7nAkXVeDYGGJLs5mIr2eeNhpS766IhSFqg7IeieSPRKoLzy2WlyiiD2r9JG4va8e0OBdey8ypk524y1EFu/xNrftOzoWF48WA+Wuanv2A1cGL43IphOSTrb/39FDVwvcQtae5BfiNlCv8ithrKS66GEDsekMxsNJcXCIXYzLhq6E6q5jAZtABWyMQo2QxuNj58xWBYNZ2F0Osm8CpFlVIodCWLwm736pVXh64+3q1LBLKpPeemXKORjfuq+C+SnG8i0Tgq1sE8n9ju5JSV/3F731Yc8+lonaoWBZO3ARnHpKQGN8zXFpASCQg19D3IfBiPymEZtiBM7Kn8JUQmzNKsL6NQDHzx0qRMOIv2LZVNKehfZIFatQ1fstpZQRwEfCks7hdMaHBzdnjxDWre/AuHUXnMT9XTs55WAF3F2Ojzl+sP/fRG+QIMXXx1jlwzUoYHHMqV1X1i9fAsSm/g3T0/PHYR72BxmiAfNn3lfALJgeuUtIQNFjRHdSlq7wQK+DJz/BhgRBdpk0QGmdFl0g2hpLscxURoH6AwgQeWYLZ32E0UblG0wY/VeiA8SNvArNKjcMwH+4PZSMOB6oitgSyjgAVHN5Q8MeVoAknJVr+MsYvZ2w60Oo3kAv8OA6wVQqs8UCn0zG/4jEM1K1DKwL9pzwx6D0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
