travis:
  secure:
    BINSTAR_TOKEN: JCf1c0ux8w6TPkLLlXsPVY59p3QAyh0inhnQpSkJozvDOh1sSIecJeAKwzO68UwXb5mlRdSoSw2ETpkdzuv7uEknZNUZRomzLWGCprIvBpjEJgK1GZy53ItKguX4xZLyxrAZsZBTQ6nMqw3seV5i5TmCnCB11hNORSN/ySD6W/FVGSFQw7h/kDaF5MN01/PPfJgzKy2vSaVyet4etqFYwM4G+nJ1/tbggmKhXAs0tNqAZNHSZtqo20JSzhLOJ3Yqehg7u5f9ffr2KhFfP6X1+sCSTMCn7A/a4wGBh6iQ8vFMRFrE4IU47aa3j/UrrPQTDEBpL2dqGFeF+sx742upHUFZs6lBmpxQ+UMarnGxFVYOIkF3snJALHEHxJAUEwjTj/G8PsikyWBYWuhHqdLDvpW6Xq3de/7PH0NNBMlORDqvxWgjTRpuc+pmM4aATNTg+2SRuzpgh0GcVYiPEaGgzbfoMmWrLIUY5rpY15jBX3pj+GR15Uuq/bxBmBQLdeJHnWj8ELHnweQXY5jCm4QrazsZ+jKi7oeS9AM0NXyCge5CvVX0anEAKFPihz6ttsn0YnVwk+zeYa3f46gYeZ3MY7VQ+i1uSd2zLcrZmnmjA0nALBAcXpn7xQad+0he3FOp0MCyVR8TrTQUuk/nLznZuntIPSxJvxEjg+U+JCtDU5g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
