travis:
  secure:
    BINSTAR_TOKEN: 5uONSnlGULQSy1FGVud/DwYivDsIJveWG3qaSJmK/lE1xVk7G+uJubl7Dz2Y04xZDJhlvTRkv+N7MM5fAAeZJElvBsyu+WMcm7LF0k80CfEtZkRcB4Elrc4pygbjjLqojH15bkSwB8GQcHW86Hq5d1AC2FoS7y8eYF6fFOnpru85ianmPrZ1QhNU2Ho4zkb0/3it1YKupURHFf2/Flvw5PpUva8B6dRaEKGsoMk79sEobshsIWZ0EafFYC0xb/MuZ2EGL2pvmwFCNf0aqV4e99/0bIGN39irP9MYUXbAFlqZCcuSHBI6WJveh6yDO3mZfiarl6+muPHl2mj4Sz1Zk76QHITOHWDFb+Hic0S1r0kG0ExNDFMD7mqcbqaz3rVqHdA936C813rVLtAHqgP43iw81nTEsfa84kDuhSWHFp1YQE2os/+fm6gqaHCFCUBIMxMJ/oE5g7CWtB6RAwtH7DK+OD1gXVLbbPTiB7EjmVG14NEJrIH6NtNqXEInnxMKB6giUq64jNFkz9qf/9X36fCztfJA3mr5yWyF53T8R8vhn2yIpYVuWwWEfGKDBkWK10wuOkUhfSuomCiq3DAyET/frwRd5oaKdOWrCTl2RtBKyPvaIGR+svoGHqatut9kXxDtHtyK7IJWpAc2NHIorhRG9+j8yDXYZganyv5rP+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
