travis:
  secure:
    BINSTAR_TOKEN: p13vrqfBbirwcR8q+b/yglZLtrxp21ZLjY0jVKt4dyyuTdoa94U868O6rYbLSyX+nZpfhNpR9J8kq/d5HJ7EpfHa3RLqu7/0n7rTuvj9F8ZGntkDIgaZEX1vWf+xozavtPfwObYkwKcVd9j0pB1a4eHuOxlbomGDSnx2hi0IeBTu+OmPRfaWlNgKfg/xZ7pMfo8rktOYVks5pjmIwmyOtfnPhkjyNpBxcd5PuPBe6Pc2Aw6lvn2L+kSeT7bHSMLxT4bWSFNNZMHgw6dnmg0hJxU9fEb9FWj8N1f/zuK1ELpTdC8b5eoIUh4usZEt8hZzYxzlaD82p21FnBWMAuRm6wUq7P4P7R2QFHXlMftcnx8xo2IocZ/1xH99OGAz6ARwtd89eTpc0hDVaFOqpTY1voFQeqV8IfNOka+GZO5YhTCnORZ8MNv5yacKxXwfnHgIo/8AZ9qJjiKTqsjcy3tOZdMVYgUyxiYXx4c9V89fGvWkBL2oVSR4pTqMXLZUQKIwm3tz7bCqPi2wXTm+2HqPuZ4dvpZOFTn2TDK4WQFDGUAy07un0aW/C1ZyrD5PzY/bff1A+CtUNlylEA5c82xw/sl+5cLn3cn5G1Y6kW+3PfPSABKG4z2cTK6eJ3gZ/kVf5YoQXUSWiZUkPUdYH9b/zavvI4eM40wRPCL/YFyipJc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
