travis:
  secure:
    BINSTAR_TOKEN: VOuoAo6KpLt10pt2bPyn+GGDW3D0HlZ0GdcZ+UuFaewJX0udRWQYUX3OMvRrwDwYUZ8w5F2g8JBjOv5HZi953Mmks3aSPa8CgLcySSTSE/1NaDOBg7vb/ZcaDJQ42geEIOSTwAnZvZaGeQgY7cEay+ERSjctcKGNTqaWS9swSYg7eCN0bdG+SqWZ0cQzTuRpDjAiYe8qo4kawQAvC6lr5i+wuWMQQXxnd42wrCvhEOO0UJyD9ZcbKZwhosPZMdrT5YsF+gp9zufZNcX4z1/x5ryLaMXrME3247RhFuJ4ZbJA+PmPmuoyWWadppSJ6ccyGJPjpBbn3f7dY2mehesN1LFawC18n16RQEN6SqUZbtgWQNg6kWLMF3l1yXQn6GDxWh1Kz4NdiucMxaHoCfkkFtvMGlBxUNKeP3vZCxdNwlW9QdDBz0LJtbB9SROaANzKrhnvfSsuprLL3zU2bHpgMmdBuc5PzpJCSxyc6h2WrkfPCiUr+nFZXzengZXUXGDlh4UZ+awGDOjHsQBJB/6Y0UDH2R0ZzQjq18rgm0qphAgJw12I14hTBqz7QxPV5nq43xKb7+FTe6JcPmphR+368dQy6/+IrzbsfI+rCGX3su7p8f7ZyfSS1punJTYm7+HuMVfu1hCwcBeyLU70I1RA0z8wyUN2WHB4XuEopOtQc8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
