travis:
  secure:
    BINSTAR_TOKEN: X9YMDm+A+7Esw63eqY6LmKDLn3od0Pza5BDIIq7ggxuY9J4WiWH/9Ob1m18QJJ5DwIspLfItOL64rnozKuUsZjNCXOGU9qfQBmJOuguL7Dnaa/W2jEDvAk4r7Zi5zp5ECt9ZDTe8lnRTlui+zU6u8Tb+7go0OvlGOSqlnI4abCEKW1p+jya0t7mtTlyzuuvJIoFF7xOyC81j8ydKI2xCVL+3s7cwnFCXqmveiIrzM+3xJc7Cy8LhFAJlN/AiKcMgM63seaiuHkXkBSLd47XbIrizrq63ecqgETPyQQss/zvDye3+RBNVQM66EfZu+TD0S/Nwi7bHpZYL4gHU0Vf+QXPN6KrX3ek4yF69vEb4lyzuiTfwM9ZdIlGBR9yMiOfdTMqsh5QuYs2H0ZrGjpcDAWEVcJ/Jzrr6Dml2/w/Ymt5CoADiPRf4tomC3RW6VvalnTEGkyMVRXtyAINqmBgbv4rkhBMBX4I+zhcmVy+Vr8O121GH7hFnnXFgIcsrZV99qJUht7oCa8yP/AGBkRScnJMeTn5bgjt7D/XfhgtyffWga1vT+haiqWDAH3m96qnVONh2V33MRm+i7DJPclG8IyVGHnK+udLnfJEuQpsAvYtCzU8xxxXJldPSmNTRWkUgVHq+nfKe/Ax5T3Xg4t4649Wco3iveErnpOPomwhfj/w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
