travis:
  secure:
    BINSTAR_TOKEN: iBh4kNNbcQZhrurPzcAkupFQIm8Ezgor3Tb4fGAySicEu5B9yPO9CzF86SR+EmQDDXWU5A9dBvF6QXiGZC3loRy1xkKMi5irnKDlS8tr38JE08eaPASNZWO4tulJ5pF0+GrYoZ3LpHb5WUg8bs935NjYGNmZCfsg/Hw5FFCN24tpNPH0RvK5Cf3Fx/Va9ye+MhdSXIEHU4XMYp57fWZc7VWx0W9iGz4HpKncGLc3tPE//scbwvh2DYn9MTmHt06KkWNnRhWnyhPiHkE2shBa7pTqNvtdwfMLdNTRAhMuF6Z31EvVZBF77fFEJ5C8YqPSLsLEp0uDXbpKH8KNb8soGQ3ruY8X8fK/e8WmFlekIdGcG18TBsViM5PPD6bGP2fk4NP+4q5UxPsMEh1QAzmDY+If9QzNhEECSmQv1r1VPBAf59cvZ10aoe/XJbmiwRULh9XF6gTwL7mVJq4sk8lu8Wnguem+uUVXs4c6QLEkJo8ztp5lQoFEtGhjdmSI1egbVTvg+nZAcKTCw89JPxdy0w7eA4zuVqTF3D2Ssz0k28k4Y3eZhzbFGpZH5EidR5Qh8KFKVlooVTqd0loun1eH/LeYTUmuS22ygvD8GcaUaEyJW3amknfUbl+2ubaBvrT3Uj5dbWPGNqlSODczrxjuX9lmpwWad7u6rKnKWGtA3jA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
