travis:
  secure:
    BINSTAR_TOKEN: e6YBhTaEkZEQBW5/ctonDEUGeQtQ9H2382GXVuKzJS7IWKeRyptHveC1zkyRJ9lJ8dtyeprtPeR/6nJdXPsXaLzid/2PvQAEqQDCqYcpM1QfQ85079cw8W13krgwR1YwxFhSSyiuGcNo7k6iWrrjuO5rARIzCmnCt/SDWBH9F1nyUe2HnUcSnXU80/IPfmZloMPibq0JsrFNvdynPG7KRLz0S6rUwZpEFiRBe0aGz0NQ92vhO3o2VDQf8tZCH+In5TRH44MSN3k2zvn+wlWiGkm/TAvUYm+82HtghUYsGWzcIpkTfEp7idlPq7EGwsu9z5cqTgpHiPom9SXoV8u9GMUofH6aUs6X6xJvSCDTO7ibAIazxzRI8bYK2ARdbABAnlaXnZGPjDa+CoiOLlBPDI3gp6Sfgw8h/CdTF/YDXpkdmBKB253fUuAm5SjWW8tb+rwtOwMXjon0jGW+Bb2iOlg4zKDd2bDqD0lCoZkBMMWi4GKvZh+GNFUTTVkE1VI+KSR4O/CCJHAHStsjKoNAl55YohochqRJW3tnpkiKVuyBNEtgsIuZu0R5IEalgtA5DNz8X0lJfuvYU9gplEl4asy7sIM8hxwB3zRXTzw8pD3dCAefiGwgNox1rNpaZ021Ef4okf/g1ZGVXb+Br0Tmkg4x2xQNViWxRf9y5nXmNnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
