travis:
  secure:
    BINSTAR_TOKEN: dZbILbFIhzrQXD7tq/PMUbRlrCeIrosUzP6VL9ZXngTUywreEqD+iAln85I1uHIGDfgQBzRWHdl70S+FAHEPrGQVY+VyDyuPJ+N8pWYShBt1roFlUYKpuAIuCgTzt1CTyrq/RXZeGBzgL/MJbeNt4AT9IRDIMUXQZeXlf+hKWF1M306SYJsvdHEprT7vSpqUPOgdgS2rIPr51N3wXXuaA6s9zzjWqbZS8yV3pIo8OGPS9x9XuX3ai2jowqhX/8SQIK+2pwMyKYC4mhnpN26gwA3tAzZgi6klG0W/Ov+jpayYBYHW2b8DgdNL0rcYNUnntHbQBJXBgcmo5CeRCW5idLhvjC6SNUyGiTkRTLZ4LS0SygOPC1k57lPPGvW8kXa3OP68jDtqPnkLfGb6Z8es/w9F91iFxB2h9Kj163gG04imNBDYeVMbvDIiOs7sWi7lXBu+j6ySex7Okms0V8VKYdtDA4uNsXPN9GiqNYQVzktarFh0SD7A8XWhtfd0nYV36Bw5AnX1iBCZ2/B04IV2mzJF0Svj11x2Dt5yEXnFlDZZAdIyB72w6/uRMzcEmmeM6ASHFIjrhTfy+SjJEBDPkXpZyQAE/h4T4Sa7yyob3JZIEsZWr2dz5HQgm+hEbHZXPtpw4ZeuwEtpZyWvBMizcKSyikNFybhvsAo5bDhwgrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
