travis:
  secure:
    BINSTAR_TOKEN: 6WUG8M46rIlCEw9qeGDHlqWqM2WkFqd2moH0XbCAgFUHk0XNCAnZkHIKtGGRDZhFZ4Sy+Zv2Uh0Iy+LjB2WquYbIGAM6WxnT0MKZP0udbH2+/+BxCLLrQzYKSxJLeZW+wuXxTXNI8ArS/lAKFYTCps966WaEQ/aAJ1hnoreas5mC8gUMP3afh9nfGQoBZHZzwL4II+GNr+U6fNOSHQm3HOmkRP/hcrAookZV9euNQmMO9iXy9GulbtmpIPVEtKHniyz6Ddr893QfMC1A6BRlhgiqWwMIcXNIU+LaEwcQQ2aHeBBGnMN8WuWNOX+fKGCOwjVIXoROkqHDu+RjN2RqXfDCuEAjaIdmH8/JylZtPri/h3E7gEhGcDSblnIyU/PeEhVYqPYTgDQN5M1RO9tIdayRd9khP40mhfz4tyqaovIMlKBEhxOTDIN6rP9/vQnS3KBF9oIbxzDx3Dlvr2i+A6Vn6tMmc3mCaSEbaEFw+zBuE2tWKYKd1dNrfojfCKHMKqDXgP4VVowO30SU2FPySCmNSiWC43pGG9uYA9XP+ZymqpNIXaJD45BrB1lgXEsRZXOQ/o+80XfGR6YKBhA766R+CW0cDf4+A/yrWRGo28D52YdaeUYFsluHwHAz+k2+A0tmaz85tkLrRG+KiVBID2lAxnoC6+u8uBuf1c8P8jA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
