travis:
  secure:
    BINSTAR_TOKEN: XYIzAvv+8bX0ql8lfyxF0nKOZSSN9yRA5nHihdDBkpd8G4N2VqNRJo5k6u08a8XVIynHXRUYBgl1s98FQrCJMNEXPvqYIjrzKwinsIrpRO/p7YROFlzQV9zUbp2Nki9JAB+SIJebe086ri4cOCgISb5U6VMWiP7rijDOin/ahk0BMSUkmQ5U5bUKkdL54hs1e4ky5yItrp9kEZ1X6JgEhqBJiNjd5/PJ+aGuNmCi9owVTlfnLikyCfhMj09Z6z06Qz85favul3cYvi9kAmXkqFfsqpIW00kYw+n/mzKMlHMlqUNGq3UgNNlvXG6vkAujLmmcpkl9IZnrquSEPpYExeoG8rnl8lnVtIZebhQQ1TI9PaDfE86MDInBVMub+FahBxFIxGmNvVCxvtNbkMxw53af/pk0Jqphf7usMBCRVNGcjei6vpD9R/n+gWtpTEUK9DsUQHE7W7sqO/jzNxl0RBpXZ6FUfTnR3o+Az8wjnhVig/IQJ2ybrRfCSxn8ovUekGsrv5Y6wSeWv8MNc9t7Sgq44ZqsnD7OLe4Eq26lUqMaN0dqwSK9bK4+yG3y9Vmcbmv1RjwWwHJX2z2aPiR2LzDUyq/8odABZT+cwzDwLReIAsPDoO1913LSP2WsjmcDEQqgB1HYnl5sD3G9CXv5yOwbxvVen+VZ4EiwJD0rLGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
