travis:
  secure:
    BINSTAR_TOKEN: rGSH6UmUt41KpEj9/P84DBY8ObToO/6j6f6YM89guoLFfoRFV+mShvyx0hlUwr+wvWNLiU6a3BYTe9UGsQAmSCnn1pEcfoeUHjaM8x75OAynVKyhKzv3wEDkUzCcXxJNQYKnYWiZz+gPFHsORF6l2csOQGcLE9Q07CrKhUiz1qcT6Ov9+gst8udYRvgCIjZuQqUpZGVIzBKsRCn9Cu1o59F3VaGirT3Lb6FNy6uxfP3/TKN3UHMgdE+get40IGPZ/hT/A8ciueqKCCE+e4Gu7Kz68x71wLBhvEvFiazbbK4s4E7zMEcWCBUxZ/bpoMqOnROxgzmMH2HaVnRo5bf8WfrE23CLJNiAtnEs7SE8eC16x0pkjQzCdY0j/vRWxD83St+Gcop05u7kRgBcAf0RGpgBuaEGvq5c03ZXBfzp8walPCG2Ascy7xY7RAmBwkIWNX6AJWMRljVvChYgRFaXZk2RIINWNu17sU2DFA0F1LXayEJuTJFEJOZ3hvtIYWQ+AQGh7hWyEPPQuPIsKNDiT5EAC7859HZTpnnmcEQVcVnhvVD81tE2Iy9RxV8/hD2EQuyhoIU9WjixbOwBwCuibLwfwWEpSAvtP2c4GS8Zt680YNSXay7uKWLk/UCKCVQc8UCpXUWYGdQN0LNzc04vU2GNzvJKWYtJgtX28Zd569Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
